import { marked } from "marked";
import DOMPurify from "dompurify";

var SDK = window.__HERMES_PLUGIN_SDK__ || {};
var React = SDK.React || window.React;
var hooks = SDK.hooks || React;
var useState = hooks.useState, useEffect = hooks.useEffect, useRef = hooks.useRef, useCallback = hooks.useCallback;
var C = SDK.components || {};
var Card = C.Card || ((p) => React.createElement("div", p));
var CardContent = C.CardContent || ((p) => React.createElement("div", p));
var CardHeader = C.CardHeader || ((p) => React.createElement("div", p));
var CardTitle = C.CardTitle || ((p) => React.createElement("div", p));
var Button = C.Button || ((p) => React.createElement("button", p));
var Input = C.Input || ((p) => React.createElement("input", p));
var Badge = C.Badge || ((p) => React.createElement("span", p));
var PLUGIN_VERSION = "2.0.2";
function afetch(url, init){ init = init || {}; var headers = new Headers(init.headers || {}); var tok = window.__HERMES_SESSION_TOKEN__ || ""; if(tok && !headers.has("X-Hermes-Session-Token")) headers.set("X-Hermes-Session-Token", tok); return fetch(url, Object.assign({}, init, { headers: headers })); }

function escAttr(v){ return String(v || "").replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); }
marked.setOptions({ gfm: true, breaks: false, renderer: (() => { const r = new marked.Renderer(); r.html = (html) => String(html.raw || html).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;"); r.link = (token) => { const href=escAttr(token.href||""); const title=token.title?` title="${escAttr(token.title)}"`:""; const text=r.parser.parseInline(token.tokens||[]); return `<a href="${href}"${title} target="_blank" rel="noopener noreferrer">${text}</a>`; }; return r; })() });
function sanitizeMarkdownHtml(html){ return DOMPurify.sanitize(html, { ADD_ATTR: ["target", "rel"] }); }

const CSS = `
.cu-root{height:calc(100vh - 110px);display:grid;grid-template-columns:260px 1fr;gap:12px;color:hsl(var(--foreground));}
.cu-sidebar,.cu-main,.cu-input{border:1px solid hsl(var(--border));border-radius:10px;background:hsl(var(--card));}
.cu-sidebar{overflow:hidden;display:flex;flex-direction:column;min-height:0}.cu-side-head{padding:12px;border-bottom:1px solid hsl(var(--border));display:flex;justify-content:space-between;align-items:center}.cu-session{padding:10px 12px;border-bottom:1px solid hsl(var(--border));cursor:pointer}.cu-session:hover,.cu-session.active{background:hsl(var(--muted))}.cu-session-title{font-weight:600;font-size:.86rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cu-session-prev{font-size:.75rem;color:hsl(var(--muted-foreground));white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cu-del{float:right;border:0;background:transparent;color:hsl(var(--muted-foreground));cursor:pointer}
.cu-main{display:flex;flex-direction:column;min-height:0}.cu-top{padding:10px 12px;border-bottom:1px solid hsl(var(--border));display:flex;justify-content:space-between;align-items:center}.cu-messages{flex:1;overflow:auto;padding:16px}.cu-row{display:flex;margin-bottom:12px}.cu-row.user{justify-content:flex-end}.cu-bubble{max-width:82%;padding:8px 12px;border-radius:10px;font-size:.875rem;line-height:1.5;word-break:break-word}.cu-row.user .cu-bubble{background:hsl(var(--primary));color:hsl(var(--primary-foreground));white-space:pre-wrap}.cu-row.assistant .cu-bubble{background:hsl(var(--muted));color:hsl(var(--foreground))}.cu-status{padding:6px 14px;color:hsl(var(--muted-foreground));font-size:.82rem;font-style:italic;display:flex;gap:6px;align-items:center}.cu-error{margin:8px 0;padding:8px 12px;background:hsl(var(--destructive) / .12);color:hsl(var(--destructive));border-radius:6px;font-size:.8rem}.cu-input{padding:10px;display:flex;gap:8px;align-items:flex-end}.cu-text{flex:1;min-height:38px}.cu-attach{display:flex;flex-wrap:wrap;gap:6px;padding:7px 0}.cu-drop{outline:2px dashed hsl(var(--primary));outline-offset:-4px}.cu-chip{display:inline-flex;align-items:center;gap:4px;padding:2px 8px;margin:2px 4px 2px 0;border:1px solid hsl(var(--border));border-radius:999px;background:hsl(var(--background));color:hsl(var(--foreground));font-size:.78rem;font-family:ui-monospace,monospace;text-decoration:none;max-width:260px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.cu-img{max-width:100%;border-radius:6px;margin:4px 0}.cu-bulk{display:inline-block;margin:6px 0;padding:4px 8px;border:1px solid hsl(var(--border));border-radius:6px;font-size:.78rem;color:hsl(var(--primary));text-decoration:none}.cu-dot{display:inline-block;width:4px;height:4px;border-radius:50%;background:currentColor;animation:cu-blink 1.2s infinite}.cu-dot:nth-child(2){animation-delay:.2s}.cu-dot:nth-child(3){animation-delay:.4s}@keyframes cu-blink{0%,80%,100%{opacity:.2}40%{opacity:1}}
.cu-md{font-size:.875rem;line-height:1.6;color:hsl(var(--foreground));overflow-wrap:anywhere}.cu-md>*:first-child{margin-top:0!important}.cu-md>*:last-child{margin-bottom:0!important}.cu-md h1,.cu-md h2,.cu-md h3,.cu-md h4{font-weight:600;margin:.75em 0 .25em;line-height:1.3}.cu-md h1{font-size:1.25rem}.cu-md h2{font-size:1.1rem}.cu-md h3{font-size:1rem}.cu-md p{margin:.4em 0}.cu-md strong{font-weight:700}.cu-md em{font-style:italic}.cu-md a{color:hsl(var(--primary));text-decoration:underline}.cu-md code{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:.82em;background:hsl(var(--background));padding:.1em .35em;border-radius:3px}.cu-md pre{background:hsl(var(--background));border:1px solid hsl(var(--border));border-radius:6px;padding:.75em 1em;overflow-x:auto;margin:.5em 0}.cu-md pre code{background:none;padding:0}.cu-md ul,.cu-md ol{padding-left:1.5em;margin:.4em 0}.cu-md blockquote{border-left:3px solid hsl(var(--border));padding-left:.75em;color:hsl(var(--muted-foreground))}.cu-md table{border-collapse:collapse;width:100%;margin:.5em 0;font-size:.82rem}.cu-md th,.cu-md td{border:1px solid hsl(var(--border));padding:.35em .65em;text-align:left}.cu-md th{background:hsl(var(--background));font-weight:600}.cu-md tbody tr:nth-child(even){background:hsl(var(--background) / .55)}
`;
function injectStyles(){ if(document.getElementById("cu-v2-style")) return; var s=document.createElement("style"); s.id="cu-v2-style"; s.textContent=CSS; document.head.appendChild(s); }
function api(path){ return (window.__HERMES_BASE_PATH__ || "") + "/api/plugins/chat-upload" + path; }
function wsUrl(path){ var proto=location.protocol==="https:"?"wss:":"ws:"; var token=window.__HERMES_SESSION_TOKEN__||""; return proto+"//"+location.host+api(path)+"?token="+encodeURIComponent(token); }
function fmtTime(ts){ if(!ts) return ""; try{return new Date(ts*1000).toLocaleString();}catch(e){return "";} }
function uuid(){ return (crypto.randomUUID ? crypto.randomUUID() : String(Date.now())+Math.random()).replace(/[^A-Za-z0-9_.-]/g,"-"); }

const MEDIA_RE=/MEDIA:([^\s]+)/g, IMG_RE=/!\[([^\]]*)\]\(([^)]+)\)/g, PATH_RE=/(?:^|\s)(\/[^\s]{2,})/g;
function parseSegments(text){ var matches=[]; function add(re,fn){ var r=new RegExp(re.source,"g"),m; while((m=r.exec(text))){ matches.push({start:m.index,end:m.index+m[0].length,seg:fn(m)}); }} add(MEDIA_RE,m=>({type:"file",path:m[1]})); add(IMG_RE,m=>({type:"image",alt:m[1],url:m[2]})); var r=new RegExp(PATH_RE.source,"g"),m; while((m=r.exec(text))){ var s=m.index+(m[0].length-m[1].length), e=s+m[1].length; if(!matches.some(x=>s<x.end&&e>x.start)) matches.push({start:s,end:e,seg:{type:"file",path:m[1]}}); } matches.sort((a,b)=>a.start-b.start); var segs=[],cur=0; matches.forEach(x=>{ if(cur<x.start) segs.push({type:"text",content:text.slice(cur,x.start)}); segs.push(x.seg); cur=x.end; }); if(cur<text.length) segs.push({type:"text",content:text.slice(cur)}); return segs.length?segs:[{type:"text",content:text||""}]; }
function fileHref(path, inline){ return api("/file?path="+encodeURIComponent(path)+(inline?"&inline=true":"")); }
function FileChip({path,onRemove}){ var name=String(path).split("/").pop()||path; return React.createElement("a",{className:"cu-chip",href:fileHref(path,false),title:path,onClick:onRemove?function(e){e.preventDefault();onRemove();}:undefined},"📎 ",name,onRemove?" ×":""); }
function AgentContent({text}){ var segs=parseSegments(text||""); var files=segs.filter(s=>s.type==="file").map(s=>s.path); return React.createElement(React.Fragment,null, files.length>=3?React.createElement("a",{className:"cu-bulk",href:api("/bulk-download"),onClick:function(e){e.preventDefault(); afetch(api("/bulk-download"),{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({paths:files})}).then(r=>r.blob()).then(b=>{var u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="chat-upload-files.zip";a.click();URL.revokeObjectURL(u);});}},"Download all (ZIP)"):null, segs.map((s,i)=>{ if(s.type==="file") return React.createElement(FileChip,{key:i,path:s.path}); if(s.type==="image") return React.createElement("img",{key:i,className:"cu-img",src:s.url,alt:s.alt}); var html=sanitizeMarkdownHtml(marked.parse(s.content||"")); return React.createElement("div",{key:i,className:"cu-md",dangerouslySetInnerHTML:{__html:html}}); })); }
function Status({label}){ if(!label) return null; return React.createElement("div",{className:"cu-status"},React.createElement("span",null,React.createElement("span",{className:"cu-dot"}),React.createElement("span",{className:"cu-dot"}),React.createElement("span",{className:"cu-dot"})),label+"…"); }
function Bubble({msg}){ var role=msg.role||"assistant"; var text=msg.text||msg.content||""; return React.createElement("div",{className:"cu-row "+role},React.createElement("div",{className:"cu-bubble"},role==="assistant"?React.createElement(AgentContent,{text:text}):text)); }

function ChatUploadPage(){
  useEffect(injectStyles,[]);
  var saved = localStorage.getItem("chat-upload.session_id") || uuid();
  if(!localStorage.getItem("chat-upload.session_id")) localStorage.setItem("chat-upload.session_id",saved);
  var [sessionId,setSessionId]=useState(saved), [sessions,setSessions]=useState([]), [messages,setMessages]=useState([]), [input,setInput]=useState(""), [busy,setBusy]=useState(false), [status,setStatus]=useState(null), [error,setError]=useState(null), [attachments,setAttachments]=useState([]), [drag,setDrag]=useState(false);
  var scrollRef=useRef(null), fileRef=useRef(null), wsRef=useRef(null);
  function loadSessions(){ afetch(api("/sessions")).then(r=>r.json()).then(d=>setSessions(d.sessions||[])).catch(()=>{}); }
  function loadSession(id){ setError(null); afetch(api("/sessions/"+encodeURIComponent(id))).then(r=>r.ok?r.json():Promise.reject()).then(d=>{ setSessionId(id); localStorage.setItem("chat-upload.session_id",id); setMessages(d.messages||d.history||[]); setAttachments([]); }).catch(()=>{ setMessages([]); }); }
  useEffect(()=>{ loadSessions(); loadSession(saved); },[]);
  useEffect(()=>{ if(scrollRef.current) scrollRef.current.scrollTop=scrollRef.current.scrollHeight; },[messages,status]);
  function saveLocal(id,msgs){ afetch(api("/sessions/"+encodeURIComponent(id)),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:msgs})}).then(loadSessions).catch(()=>{}); }
  function newChat(){ var id=uuid(); setSessionId(id); localStorage.setItem("chat-upload.session_id",id); setMessages([]); setAttachments([]); setInput(""); }
  function deleteSession(id,e){ e.stopPropagation(); afetch(api("/sessions/"+encodeURIComponent(id)),{method:"DELETE"}).then(()=>{ loadSessions(); if(id===sessionId) newChat(); }); }
  function uploadFiles(files){ Array.from(files||[]).forEach(file=>{ var fd=new FormData(); fd.append("session_id",sessionId); fd.append("file",file); afetch(api("/upload"),{method:"POST",body:fd}).then(r=>r.ok?r.json():r.text().then(t=>Promise.reject(t))).then(d=>{ setAttachments(a=>a.concat([d])); }).catch(e=>setError(String(e))); }); }
  function paste(e){ var items=e.clipboardData&&e.clipboardData.items; if(!items) return; var files=[]; for(var i=0;i<items.length;i++){ if(items[i].kind==="file") files.push(items[i].getAsFile()); } if(files.length){ e.preventDefault(); uploadFiles(files); } }
  var send=useCallback(function(){ var text=input.trim(); if(!text&&!attachments.length||busy) return; var mediaText=attachments.map(a=>"MEDIA:"+a.path).join("\n"); var full=[text,mediaText].filter(Boolean).join("\n"); var userMsg={role:"user",text:full,timestamp:Date.now()/1000,attachments:attachments}; var next=messages.concat([userMsg]); setMessages(next); saveLocal(sessionId,next); setInput(""); setAttachments([]); setBusy(true); setStatus("thinking"); setError(null); var chunks=[]; var ws=new WebSocket(wsUrl("/stream")); wsRef.current=ws; ws.onopen=function(){ ws.send(JSON.stringify({type:"message",text:full,session_id:sessionId,attachments:attachments})); }; ws.onmessage=function(evt){ var f; try{f=JSON.parse(evt.data)}catch(e){return} if(f.type==="session"&&f.session_id){setSessionId(f.session_id);localStorage.setItem("chat-upload.session_id",f.session_id)} else if(f.type==="status") setStatus(f.label||null); else if(f.type==="delta") chunks.push(f.text||""); else if(f.type==="done"){ var final=f.text||chunks.join(""); var doneMsgs=next.concat([{role:"assistant",text:final,timestamp:Date.now()/1000,attachments:[]}]); setMessages(doneMsgs); saveLocal(sessionId,doneMsgs); setStatus(null); loadSessions(); } else if(f.type==="clear") setStatus(null); else if(f.type==="error"){ setError(f.text||"Agent error"); setStatus(null); } }; ws.onerror=function(){ setError("Connection error. Restart dashboard and retry if the plugin was just updated."); setBusy(false); setStatus(null); }; ws.onclose=function(){ setBusy(false); setStatus(null); wsRef.current=null; }; },[input,attachments,busy,messages,sessionId]);
  function key(e){ if(e.key==="Enter"&&!e.shiftKey){ e.preventDefault(); send(); }}
  return React.createElement("div",{className:"cu-root",onPaste:paste,onDragOver:e=>{e.preventDefault();setDrag(true)},onDragLeave:()=>setDrag(false),onDrop:e=>{e.preventDefault();setDrag(false);uploadFiles(e.dataTransfer.files)}},
    React.createElement("div",{className:"cu-sidebar"},React.createElement("div",{className:"cu-side-head"},React.createElement("b",null,"Sessions"),React.createElement(Button,{onClick:newChat},"New")),React.createElement("div",{style:{overflow:"auto"}},sessions.map(s=>React.createElement("div",{key:s.session_id,className:"cu-session "+(s.session_id===sessionId?"active":""),onClick:()=>loadSession(s.session_id)},React.createElement("button",{className:"cu-del",onClick:(e)=>deleteSession(s.session_id,e),title:"Delete"},"×"),React.createElement("div",{className:"cu-session-title"},s.title||"New chat"),React.createElement("div",{className:"cu-session-prev"},s.preview||"No messages"),React.createElement("div",{className:"cu-session-prev"},fmtTime(s.updated_at)))))),
    React.createElement("div",{className:"cu-main "+(drag?"cu-drop":"")},React.createElement("div",{className:"cu-top"},React.createElement("div",null,React.createElement("b",null,"Chat")," ",React.createElement(Badge,{variant:"outline"},"v"+PLUGIN_VERSION))),React.createElement("div",{className:"cu-messages",ref:scrollRef},messages.length?messages.map((m,i)=>React.createElement(Bubble,{key:i,msg:m})):React.createElement("div",{style:{height:"100%",display:"flex",alignItems:"center",justifyContent:"center",color:"hsl(var(--muted-foreground))",fontStyle:"italic"}},"Send a message, paste an image, or drop a file."),React.createElement(Status,{label:status})),error?React.createElement("div",{className:"cu-error"},error):null,React.createElement("div",{className:"cu-input"},React.createElement("input",{ref:fileRef,type:"file",multiple:true,style:{display:"none"},onChange:e=>uploadFiles(e.target.files)}),React.createElement("div",{style:{flex:1}},React.createElement(Input,{className:"cu-text",value:input,onChange:e=>setInput(e.target.value),onKeyDown:key,placeholder:busy?"Agent is working…":"Type a message. Paste image or drop file to attach.",disabled:busy,style:{width:"100%"}}),attachments.length?React.createElement("div",{className:"cu-attach"},attachments.map((a,i)=>React.createElement(FileChip,{key:i,path:a.path,onRemove:()=>setAttachments(x=>x.filter((_,j)=>j!==i))}))):null),React.createElement(Button,{onClick:()=>fileRef.current&&fileRef.current.click(),disabled:busy},"Attach"),React.createElement(Button,{onClick:send,disabled:busy||(!input.trim()&&!attachments.length)},busy?"Working…":"Send"))))
}

window.__HERMES_PLUGINS__.register("chat-upload", ChatUploadPage);
